package com.pi.xerosync.dbconnect;

/**
 * User: thomas Date: 18/02/14
 */
public interface PatriciaExportSchema {
  final String SCHEMA_NAME = "dbo";

  final String PAT_NAMES_ADDRESS_TYPE_TABLE = "PAT_NAMES_ADDRESS_TYPE";
  final String CREATE_TAB_PAT_NAMES_ADDRESS_TYPE = "CREATE TABLE dbo.PAT_NAMES_ADDRESS_TYPE (\n"
                                                   + "\tADDRESS_TYPE_ID int NOT NULL,\n"
                                                   + "\tADDRESS_TYPE_LABEL nvarchar(60) NOT NULL,\n"
                                                   + "\tSORT_ORDER int NOT NULL,\n"
                                                   + "\tDEFAULT_FINANCIAL_ADDRESS int,\n"
                                                   + "\tPRIMARY KEY (ADDRESS_TYPE_ID)\n"
                                                   + ");";

  final String PAT_NAMES_TABLE = "PAT_NAMES";
  final String CREATE_TAB_PAT_NAMES = "CREATE TABLE dbo.PAT_NAMES (\n"
                                      + "\tNAME_ID int NOT NULL,\n"
                                      + "\tOLD_CLIENT_NUMBER1 nvarchar(30),\n"
                                      + "\tIS_LEGAL_ENTITY int NOT NULL,\n"
                                      + "\tIS_MALE int,\n"
                                      + "\tEMPLOYMENT_TYPE int,\n"
                                      + "\tNAME_CREATED_DATE datetime NOT NULL,\n"
                                      + "\tNAME_EDIT_DATE datetime NOT NULL,\n"
                                      + "\tNAME_CREATED_BY nvarchar(20) NOT NULL,\n"
                                      + "\tNAME_EDITED_BY nvarchar(20) NOT NULL,\n"
                                      + "\tNAME_BIRTH_DAY datetime,\n"
                                      + "\tNATIONALITY_ID nvarchar(2),\n"
                                      + "\tNAME_REMARK nvarchar(65),\n"
                                      + "\tSTATUS_TEXT nvarchar(10),\n"
                                      + "\tASSOCIATED_NAME_ID int,\n"
                                      + "\tCATEGORY_ID nvarchar(20),\n"
                                      + "\tBLOCK_CODE nvarchar(1),\n"
                                      + "\tACTOR_INACTIVE int,\n"
                                      + "\tCLIENT_RESPONSIBLE_PERSON nvarchar(40),\n"
                                      + "\tCLIENT_RESPONSIBLE_PERSON_V nvarchar(40),\n"
                                      + "\tGPA_NO nvarchar(20),\n"
                                      + "\tLINE_OF_BUSINESS nvarchar(50),\n"
                                      + "\tBATCHJOB_LIST_REPORT nvarchar(40),\n"
                                      + "\tBATCHJOB_LIST_LETTER_ID nvarchar(10),\n"
                                      + "\tIS_APPLICANT int,\n"
                                      + "\tIS_ASSOCIATE nvarchar(1),\n"
                                      + "\tRECOMENDED_NAME_TYPE_ID int,\n"
                                      + "\tVAT_CODE_ID int,\n"
                                      + "\tPRICE_LIST_ID int,\n"
                                      + "\tCURRENCY_ID nvarchar(3),\n"
                                      + "\tINC_CURRENCY_ID nvarchar(3),\n"
                                      + "\tJOURNAL_ID nvarchar(2),\n"
                                      + "\tCREDIT_LIMIT numeric(14,2),\n"
                                      + "\tCREDIT_TIME int,\n"
                                      + "\tCREDIT_RATING nvarchar(65),\n"
                                      + "\tDISCOUNT numeric(14,2),\n"
                                      + "\tFIXED_HOURLY_RATE numeric(14,2),\n"
                                      + "\tNUMBER_OF_DEMANDS int,\n"
                                      + "\tACTOR_TOTAL_CHARGED_AMOUNT numeric(14,2),\n"
                                      + "\tACTOR_TOTAL_LAST_YEAR numeric(14,2),\n"
                                      + "\tAMOUNT numeric(14,2),\n"
                                      + "\tDUE_NOT_PAYED_AMOUNT numeric(14,2),\n"
                                      + "\tADVANCE_AMOUNT numeric(14,2),\n"
                                      + "\tORGANISATION_NUMBER nvarchar(60),\n"
                                      + "\tACN_NUMBER nvarchar(60),\n"
                                      + "\tOHIM_NUMBER nvarchar(60),\n"
                                      + "\tPROFILE nvarchar(30),\n"
                                      + "\tENTITY_SIZE nvarchar(1),\n"
                                      + "\tCLIENT_TAX_RENEWAL_REMINDER_TM int,\n"
                                      + "\tCLIENT_TAX_RENEWAL_DEBIT_TM_DE int,\n"
                                      + "\tCLIENT_OTHER_DEBIT_TM_DESIGN_I int,\n"
                                      + "\tCOPIES_DEBNOTE_NUMBER int,\n"
                                      + "\tCOPIES_CORR_NUMBER int,\n"
                                      + "\tIS_CLIENT_FILE_IN_ARCHIVE int,\n"
                                      + "\tIS_TM_DESIGN_IN_ARCHIVE int,\n"
                                      + "\tIS_RELATED_DESIGN_EXIST int,\n"
                                      + "\tIS_PERMANENT_INSTR_PAY_TAX_TM int,\n"
                                      + "\tIS_COLLECT_DEBIT_ALLOWED int,\n"
                                      + "\tREMINDER nvarchar(1),\n"
                                      + "\tINTEREST_INVOICE numeric(1),\n"
                                      + "\tTHIRD_PARTY int,\n"
                                      + "\tLEGAL_STATUS nvarchar(130),\n"
                                      + "\tBATCH_CYCLE int,\n"
                                      + "\tMATTERS_COUNTER int,\n"
                                      + "\tWEBUSER int,\n"
                                      + "\tWEB_UID nvarchar(40),\n"
                                      + "\tWEB_PW nvarchar(30),\n"
                                      + "\tACTIVE_IN_ALL_COUNTRIES int,\n"
                                      + "\tLOGIN_ID nvarchar(20),\n"
                                      + "\tWEB_LOGIN_VALID_FROM_DATE datetime,\n"
                                      + "\tWEB_LOGIN_VALID_TO_DATE datetime,\n"
                                      + "\tBATCHJOB_LIST_REPORT_NUMERIC int,\n"
                                      + "\tCASE_REFERENCE int,\n"
                                      + "\tCOLL_CORR_METHOD int,\n"
                                      + "\tPRIMARY KEY (NAME_ID)\n"
                                      + ");\n"
                                      + "\n"
                                      + "ALTER TABLE dbo.PAT_NAMES\n"
                                      + "\tADD FOREIGN KEY (ASSOCIATED_NAME_ID) \n"
                                      + "\tREFERENCES PAT_NAMES (NAME_ID);\n"
                                      + "\n";

  final String PAT_NAMES_ADDRESS_TABLE = "PAT_NAMES_ADDRESS";
  final String CREATE_TAB_PAT_NAMES_ADDRESS = "CREATE TABLE dbo.PAT_NAMES_ADDRESS (\n"
                                              + "\tADDRESS_ID int NOT NULL,\n"
                                              + "\tNAME_ID int NOT NULL,\n"
                                              + "\tADDRESS_TYPE_ID int NOT NULL,\n"
                                              + "\tIS_DEFAULT int NOT NULL,\n"
                                              + "\tCURRENT_ONE int NOT NULL,\n"
                                              + "\tLOG_ENTRY int NOT NULL,\n"
                                              + "\tLOG_DATE datetime,\n"
                                              + "\tLANGUAGE_ID int NOT NULL,\n"
                                              + "\tADDRESS_ID_CREATED_DATE datetime NOT NULL,\n"
                                              + "\tADDRESS_ID_EDIT_DATE datetime NOT NULL,\n"
                                              + "\tADDRESS_ID_CREATED_BY nvarchar(20) NOT NULL,\n"
                                              + "\tADDRESS_ID_EDITED_BY nvarchar(20) NOT NULL,\n"
                                              + "\tADR1 nvarchar(100),\n"
                                              + "\tADR2 nvarchar(100),\n"
                                              + "\tADR3 nvarchar(100),\n"
                                              + "\tPOSTAL_CODE nvarchar(100),\n"
                                              + "\tPOSTADDRESS_CITY nvarchar(65),\n"
                                              + "\tPOSTADDRESS_REGION nvarchar(65),\n"
                                              + "\tZIP_CODE nvarchar(65),\n"
                                              + "\tADR4 nvarchar(100),\n"
                                              + "\tADR5 nvarchar(100),\n"
                                              + "\tCORRESPONDANCE_METHOD int,\n"
                                              + "\tUSE_LANGUAGE_SUBSET int,\n"
                                              + "\tHEADER_FOOTER_LETTER_ID nvarchar(10),\n"
                                              + "\tSTATE_ID nvarchar(2) NOT NULL,\n"
                                              + "\tSTA_STATE_ID nvarchar(2),\n"
                                              + "\tTELEPHONE nvarchar(30),\n"
                                              + "\tTELEPHONE_2 nvarchar(30),\n"
                                              + "\tTELEPHONE_3 nvarchar(30),\n"
                                              + "\tTELEPHONE_MOBILE nvarchar(30),\n"
                                              + "\tTELEPHONE_MOBILE2 nvarchar(30),\n"
                                              + "\tTELEFAX nvarchar(30),\n"
                                              + "\tTELEFAX2 nvarchar(30),\n"
                                              + "\tE_MAIL_ADRESS nvarchar(100),\n"
                                              + "\tWWW nvarchar(100),\n"
                                              + "\tACTIVE_FROM_DATE datetime,\n"
                                              + "\tE_MAIL_ADRESS_CC nvarchar(100),\n"
                                              + "\tE_MAIL_ADRESS_BCC nvarchar(100),\n"
                                              + "\tPRIMARY KEY (ADDRESS_ID)\n"
                                              + ");\n";

  final String EXACT_P_S_JOURNAL_TABLE = "EXACT_P_S_JOURNAL";
  final String CREATE_TAB_EXACT_P_S_JOURNAL = "CREATE TABLE dbo.EXACT_P_S_JOURNAL (\n"
                                              + "\tPSJ_SAVED_DATE datetime NOT NULL,\n"
                                              + "\tPSJ_EXPORTED_DATE datetime,\n"
                                              + "\tPSJ_LINE_NUMBER int NOT NULL,\n"
                                              + "\tPSJ_JOURNAL_TYPE nvarchar(1) NOT NULL,\n"
                                              + "\tPSJ_JOURNAL_NUMBER nvarchar(2) NOT NULL,\n"
                                              + "\tPSJ_PERIOD nvarchar(150),\n"
                                              + "\tPSJ_FINANCIAL_YEAR nvarchar(150),\n"
                                              + "\tPSJ_ENTRY_NUMBER nvarchar(150),\n"
                                              + "\tPSJ_DESCRIPTION nvarchar(150),\n"
                                              + "\tPSJ_DATE nvarchar(150),\n"
                                              + "\tPSJ_GENERAL_LEDGER_ACCOUNT nvarchar(150),\n"
                                              + "\tPSJ_OFFSET_ACCOUNT nvarchar(150),\n"
                                              + "\tPSJ_DEBTOR_NUMBER nvarchar(150),\n"
                                              + "\tPSJ_CREDITOR_NUMBER nvarchar(150),\n"
                                              + "\tPSJ_OUTSTANDING_INVOICE_NUM nvarchar(150),\n"
                                              + "\tPSJ_AMOUNT nvarchar(150),\n"
                                              + "\tPSJ_JOURNALIZE_FC nvarchar(150),\n"
                                              + "\tPSJ_CURRENCY nvarchar(150),\n"
                                              + "\tPSJ_EXCHANGE_RATE nvarchar(150),\n"
                                              + "\tPSJ_PAYMENT_CHARGE_DISCOUNT nvarchar(150),\n"
                                              + "\tPSJ_AMOUNT_P_C_D nvarchar(150),\n"
                                              + "\tPSJ_DUE_DATE_INVOICE nvarchar(150),\n"
                                              + "\tPSJ_DUE_DATE_PAYMENT nvarchar(150),\n"
                                              + "\tPSJ_VAT_CODE nvarchar(150),\n"
                                              + "\tPSJ_VAT_AMOUNT nvarchar(150),\n"
                                              + "\tPSJ_WEEK_NUMBER nvarchar(150),\n"
                                              + "\tPSJ_PAYMENT_REF nvarchar(150),\n"
                                              + "\tPSJ_PAYMENT_METHOD nvarchar(150),\n"
                                              + "\tPSJ_AMOUNT_BLOCKED_ACCOUNT nvarchar(150),\n"
                                              + "\tPSJ_COST_CENTER nvarchar(150),\n"
                                              + "\tPSJ_COST_UNIT nvarchar(150),\n"
                                              + "\tPSJ_QUANTITY nvarchar(150),\n"
                                              + "\tPSJ_WRITE_OFF_CODE nvarchar(150),\n"
                                              + "\tPSJ_REVERSAL_ENTRY nvarchar(150),\n"
                                              + "\tPSJ_PROJECT_CODE nvarchar(150),\n"
                                              + "\tPSJ_AMOUNT_REVENUE nvarchar(150),\n"
                                              + "\tPSJ_AMOUNT_EXPENSES nvarchar(150),\n"
                                              + "\tPSJ_NUMBER_OF_REVENUES nvarchar(150),\n"
                                              + "\tPSJ_NUMBER_OF_EXPENSES nvarchar(150),\n"
                                              + "\tPSJ_COST_CENTER_2 nvarchar(150),\n"
                                              + "\tPSJ_PROJECT_DESCRIPTION nvarchar(150),\n"
                                              + "\tPSJ_COST_CATEGORY nvarchar(150),\n"
                                              + "\tPSJ_JOURNAL_LABEL nvarchar(150),\n"
                                              + "\tPSJ_CATEGORY_TYPE nvarchar(150),\n"
                                              + "\tPSJ_CASE_COUNTRY_CODE nvarchar(150),\n"
                                              + "\tPSJ_CASE_TYPE nvarchar(150),\n"
                                              + "\tPSJ_SAVED_DATE_STR nvarchar(150),\n"
                                              + "\tPSJ_DUE_DATE_INVOICE_STR nvarchar(150),\n"
                                              + "\tPSJ_DUE_DATE_PAYMENT_STR nvarchar(150),\n"
                                              + "\tPSJ_TRANS_ID int,\n"
                                              + "\tPSJ_CASE_ID int,\n"
                                              + "\tPSJ_CHECKSUM nvarchar(150),\n"
                                              + "\tPSJ_WORKCODE nvarchar(150),\n"
                                              + "\tPSJ_LOGINID nvarchar(150),\n"
                                              + "\tPSJ_DEP_COSTCENTER nvarchar(150),\n"
                                              + "\tPSJ_OLD_CASE_ID nvarchar(150),\n"
                                              + "\tPSJ_WORKCODE_TYPE nvarchar(150),\n"
                                              + "\tPSJ_COMMENT nvarchar(250),\n"
                                              + "\tPSJ_LOGINID_REG nvarchar(20),\n"
                                              + "\tPSJ_KID_CODE nvarchar(150),\n"
                                              + "\tPRIMARY KEY (PSJ_JOURNAL_NUMBER,PSJ_JOURNAL_TYPE,PSJ_LINE_NUMBER,PSJ_SAVED_DATE)\n"
                                              + ");\n";

  final String EXACT_ACTOR_TABLE = "EXACT_ACTOR";
  final String CREATE_TAB_EXACT_ACTOR = "CREATE TABLE dbo.EXACT_ACTOR (\n"
                                        + "\tEX_SAVED_DATE datetime NOT NULL,\n"
                                        + "\tEX_EXPORTED_DATE datetime NOT NULL,\n"
                                        + "\tEX_ACTOR_ID nvarchar(6) NOT NULL,\n"
                                        + "\tEX_NAME nvarchar(150),\n"
                                        + "\tEX_ADRESS_1 nvarchar(150),\n"
                                        + "\tEX_ADRESS_2 nvarchar(150),\n"
                                        + "\tEX_ADRESS_3 nvarchar(150),\n"
                                        + "\tEX_POSTCODE nvarchar(150),\n"
                                        + "\tEX_CITY nvarchar(150),\n"
                                        + "\tEX_COUNTRY nvarchar(150),\n"
                                        + "\tEX_SEARCH_CODE nvarchar(150),\n"
                                        + "\tEX_CURRENCY nvarchar(150),\n"
                                        + "\tEX_TELEPHONE nvarchar(150),\n"
                                        + "\tEX_TELEFAX nvarchar(150),\n"
                                        + "\tEX_CONTACT nvarchar(150),\n"
                                        + "\tEX_SEX nvarchar(150),\n"
                                        + "\tEX_TITLE_CODE nvarchar(150),\n"
                                        + "\tEX_INITIALS nvarchar(150),\n"
                                        + "\tEX_JOB_SPEC nvarchar(150),\n"
                                        + "\tEX_TEL_CONTACT nvarchar(150),\n"
                                        + "\tEX_BANK_ACCOUNT nvarchar(150),\n"
                                        + "\tEX_BLOCKED_ACCOUNT nvarchar(150),\n"
                                        + "\tEX_BANK_NAME nvarchar(150),\n"
                                        + "\tEX_POSTBANK_ACCOUNT_DEBTOR nvarchar(150),\n"
                                        + "\tEX_POSTBANK_ACCOUNT_CREDITOR nvarchar(150),\n"
                                        + "\tEX_PAYMENT_METHOD nvarchar(150),\n"
                                        + "\tEX_OFFSET_ACCOUNT nvarchar(150),\n"
                                        + "\tEX_JOURNAL nvarchar(150),\n"
                                        + "\tEX_ATTENTION_FIELD nvarchar(150),\n"
                                        + "\tEX_CATEGORY nvarchar(150),\n"
                                        + "\tEX_INVOICE_DEBTOR nvarchar(150),\n"
                                        + "\tEX_CREDIT_LIMIT numeric(8,2),\n"
                                        + "\tEX_REMINDER nvarchar(150),\n"
                                        + "\tEX_PAYMENT_CONDITION nvarchar(150),\n"
                                        + "\tEX_BLOCK nvarchar(150),\n"
                                        + "\tEX_CUSTOMER_CODE nvarchar(150),\n"
                                        + "\tEX_REPRESENTATIVE nvarchar(150),\n"
                                        + "\tEX_PRICE_LIST nvarchar(150),\n"
                                        + "\tEX_EXTRA_ITEM_CODE nvarchar(150),\n"
                                        + "\tEX_DELIVERY_METHOD nvarchar(150),\n"
                                        + "\tEX_DISCOUNT_PERCENTAGE numeric(10,6),\n"
                                        + "\tEX_DATE_LAST_REMINDER nvarchar(150),\n"
                                        + "\tEX_LAYOUT_CODE nvarchar(150),\n"
                                        + "\tEX_LANGUAGE nvarchar(150),\n"
                                        + "\tEX_DEBET_BAL_CURR_FIN_YEAR numeric(8,2),\n"
                                        + "\tEX_CREDIT_BAL_CURR_FIN_YEAR numeric(8,2),\n"
                                        + "\tEX_DEBET_BAL_SECOND_FIN_YEAR numeric(8,2),\n"
                                        + "\tEX_CREDIT_BAL_SECOND_FIN_YEAR numeric(8,2),\n"
                                        + "\tEX_DEBET_BAL_POSTED numeric(8,2),\n"
                                        + "\tEX_CREDIT_BAL_POSTED numeric(8,2),\n"
                                        + "\tEX_REV_EXCL_VAT_CURR_FIN_YEAR numeric(8,2),\n"
                                        + "\tEX_REV_INCL_VAT_CURR_FIN_YEAR numeric(8,2),\n"
                                        + "\tEX_REV_EXCL_VAT_PREV_FIN_YEAR numeric(8,2),\n"
                                        + "\tEX_REV_INCL_VAT_PREV_FIN_YEAR numeric(8,2),\n"
                                        + "\tEX_AMOUNT_ON_ORDER numeric(8,2),\n"
                                        + "\tEX_FACTORING nvarchar(150),\n"
                                        + "\tEX_VAT_NUMBER nvarchar(150),\n"
                                        + "\tEX_CHECK_DATE nvarchar(150),\n"
                                        + "\tEX_ROLE_TYPE_TYPE_ID nvarchar(6) NOT NULL,\n"
                                        + "\tEX_VAT_TRANSACTION nvarchar(150),\n"
                                        + "\tEX_VAT_TRANS_ADJ nvarchar(150),\n"
                                        + "\tEX_NAME3 nvarchar(150),\n"
                                        + "\tEX_TELEPHONE_HOME nvarchar(150),\n"
                                        + "\tEX_TELEPHONE_MOBILE nvarchar(150),\n"
                                        + "\tEX_TELEX nvarchar(150),\n"
                                        + "\tEX_E_MAIL_ADRESS nvarchar(150),\n"
                                        + "\tEX_WWW nvarchar(150),\n"
                                        + "\tEX_NAME2 nvarchar(150),\n"
                                        + "\tEX_TRANS_ID int,\n"
                                        + "\tEX_ZIP_CODE nvarchar(150),\n"
                                        + "\tEX_POSTADDRESS_CITY nvarchar(150),\n"
                                        + "\tEX_POSTADDRESS_REGION nvarchar(150),\n"
                                        + "\tEX_ADDRESS_ID int,\n"
                                        + "\tEX_ENTITY_ID int,\n"
                                        + "\tPRIMARY KEY (EX_ACTOR_ID,EX_EXPORTED_DATE,EX_ROLE_TYPE_TYPE_ID,EX_SAVED_DATE)\n"
                                        + ");";


  final String PAT_NAMES_ENTITY_TABLE = "PAT_NAMES_ENTITY";
  final String CREATE_TAB_PAT_NAMES_ENTITY = "CREATE TABLE dbo.PAT_NAMES_ENTITY (\n"
                                             + "\tENTITY_ID int NOT NULL,\n"
                                             + "\tNAME_ID int NOT NULL,\n"
                                             + "\tCURRENT_ONE int NOT NULL,\n"
                                             + "\tLOG_ENTRY int NOT NULL,\n"
                                             + "\tLOG_DATE datetime,\n"
                                             + "\tENTITY_ID_CREATED_DATE datetime NOT NULL,\n"
                                             + "\tENTITY_ID_EDIT_DATE datetime NOT NULL,\n"
                                             + "\tENTITY_ID_CREATED_BY nvarchar(20) NOT NULL,\n"
                                             + "\tENTITY_ID_EDITED_BY nvarchar(20) NOT NULL,\n"
                                             + "\tNAME1 nvarchar(120) NOT NULL,\n"
                                             + "\tNAME2 nvarchar(120),\n"
                                             + "\tNAME3 nvarchar(120),\n"
                                             + "\tNAME_ATTENTION nvarchar(120),\n"
                                             + "\tOFFICIAL_NAME_NEW nvarchar(250),\n"
                                             + "\tTITLE nvarchar(150),\n"
                                             + "\tGREETING_TEXT nvarchar(100),\n"
                                             + "\tSIGN_OF_TEXT nvarchar(100),\n"
                                             + "\tLOGOTYPE_FILENAME nvarchar(100),\n"
                                             + "\tNAME_PREFIX nvarchar(15),\n"
                                             + "\tNAME_SUFFIX nvarchar(15),\n"
                                             + "\tACTIVE_FROM_DATE datetime,\n"
                                             + "\tPRIMARY KEY (ENTITY_ID)\n"
                                             + ");\n"
                                             + "\n"
                                             + "ALTER TABLE dbo.PAT_NAMES_ENTITY\n"
                                             + "\tADD FOREIGN KEY (NAME_ID) \n"
                                             + "\tREFERENCES PAT_NAMES (NAME_ID);";


  final String PAT_CONNECTION_POOL_TABLE = "PAT_CONNECTION_POOL";
  final String CREATE_TAB_PAT_CONNECTION_POOL = "CREATE TABLE dbo.PAT_CONNECTION_POOL (\n"
                                                + "\tCONNECTION_ID int NOT NULL,\n"
                                                + "\tLOGIN_ID nvarchar(20) NOT NULL,\n"
                                                + "\tCOMPUTER_ID nvarchar(30) NOT NULL,\n"
                                                + "\tLOGIN_DATE datetime NOT NULL,\n"
                                                + "\tLAST_ACTIVITY datetime NOT NULL,\n"
                                                + "\tMARKED_DEAD int NOT NULL,\n"
                                                + "\tLOGOFF_DATE datetime,\n"
                                                + "\tFRAME_HANDLE int,\n"
                                                + "\tPRIMARY KEY (CONNECTION_ID)\n"
                                                + ");";

  final String WORK_GROUP_TABLE = "WORK_GROUP";
  final String CREATE_TAB_WORK_GROUP = "CREATE TABLE dbo.WORK_GROUP (\n"
                                       + "\tCASE_ID int NOT NULL,\n"
                                       + "\tWORK_GROUP_LABEL nvarchar(30),\n"
                                       + "\tTEAM_ID int,\n"
                                       + "\tPRIMARY KEY (CASE_ID)\n"
                                       + ");\n";

  final String TEAM_EFFORT_TABLE = "TEAM_EFFORT";
  final String CREATE_TAB_TEAM_EFFORT = "CREATE TABLE dbo.TEAM_EFFORT (\n"
                                        + "\tTEAM_ID int NOT NULL,\n"
                                        + "\tLOGIN_ID nvarchar(20) NOT NULL,\n"
                                        + "\tROLE_ID int NOT NULL,\n"
                                        + "\tIS_TEAM_LEADER numeric(1),\n"
                                        + "\tDOCKETING_DISTRIBUTION numeric(1),\n"
                                        + "\tDOCKETING_PROCESS numeric(1),\n"
                                        + "\tPRIMARY KEY (LOGIN_ID,ROLE_ID,TEAM_ID)\n"
                                        + ");";



}
