package com.pi.xerosync.xeroservice;

import com.pi.xerosync.PatriciaDbAbstractTest;
import com.pi.xerosync.common.InvoiceDataExtractor;
import com.pi.xerosync.common.PatriciaInvoice;
import com.pi.xerosync.common.TransactionType;
import com.pi.xerosync.dbconnect.DbTestUtils;
import com.pi.xerosync.dbservice.PatriciaExactPSJournalGateway;
import com.rossjourdain.jaxb.Contact;
import com.rossjourdain.jaxb.Invoice;
import com.rossjourdain.jaxb.LineItem;

import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.io.IOException;
import java.sql.SQLException;
import java.util.List;

/**
 * User: thomas Date: 18/02/14
 */
public class XeroFromPatriciaTransformerTest extends PatriciaDbAbstractTest {

  protected PatriciaExactPSJournalGateway exactTableGateway;
  protected InvoiceDataExtractor invoiceDataExtractor;
  protected XeroFromPatriciaTransformer xeroFromPatriciaTransformer;

  @BeforeMethod
  public void setUp() throws IOException, SQLException {
    super.setup(new GatewayModule());
    exactTableGateway = injector.getInstance(PatriciaExactPSJournalGateway.class);
    invoiceDataExtractor = injector.getInstance(InvoiceDataExtractor.class);
    xeroFromPatriciaTransformer = injector.getInstance(XeroFromPatriciaTransformer.class);
  }

  @AfterMethod
  public void tearDown() {
    super.tearDown();
  }

  @Test
  public void testAPToMultipleMatters() throws Exception {
    DbTestUtils.executeSql(connectionManager.getDataSource(),
                           "INSERT INTO dbo.EXACT_P_S_JOURNAL(PSJ_SAVED_DATE, PSJ_EXPORTED_DATE, PSJ_LINE_NUMBER, PSJ_JOURNAL_TYPE, PSJ_JOURNAL_NUMBER, PSJ_PERIOD, PSJ_FINANCIAL_YEAR, PSJ_ENTRY_NUMBER, PSJ_DESCRIPTION, PSJ_DATE, PSJ_GENERAL_LEDGER_ACCOUNT, PSJ_OFFSET_ACCOUNT, PSJ_DEBTOR_NUMBER, PSJ_CREDITOR_NUMBER, PSJ_OUTSTANDING_INVOICE_NUM, PSJ_AMOUNT, PSJ_JOURNALIZE_FC, PSJ_CURRENCY, PSJ_EXCHANGE_RATE, PSJ_PAYMENT_CHARGE_DISCOUNT, PSJ_AMOUNT_P_C_D, PSJ_DUE_DATE_INVOICE, PSJ_DUE_DATE_PAYMENT, PSJ_VAT_CODE, PSJ_VAT_AMOUNT, PSJ_WEEK_NUMBER, PSJ_PAYMENT_REF, PSJ_PAYMENT_METHOD, PSJ_AMOUNT_BLOCKED_ACCOUNT, PSJ_COST_CENTER, PSJ_COST_UNIT, PSJ_QUANTITY, PSJ_WRITE_OFF_CODE, PSJ_REVERSAL_ENTRY, PSJ_PROJECT_CODE, PSJ_AMOUNT_REVENUE, PSJ_AMOUNT_EXPENSES, PSJ_NUMBER_OF_REVENUES, PSJ_NUMBER_OF_EXPENSES, PSJ_COST_CENTER_2, PSJ_PROJECT_DESCRIPTION, PSJ_COST_CATEGORY, PSJ_JOURNAL_LABEL, PSJ_CATEGORY_TYPE, PSJ_CASE_COUNTRY_CODE, PSJ_CASE_TYPE, PSJ_SAVED_DATE_STR, PSJ_DUE_DATE_INVOICE_STR, PSJ_DUE_DATE_PAYMENT_STR, PSJ_TRANS_ID, PSJ_CASE_ID, PSJ_CHECKSUM, PSJ_WORKCODE, PSJ_LOGINID, PSJ_DEP_COSTCENTER, PSJ_OLD_CASE_ID, PSJ_WORKCODE_TYPE, PSJ_COMMENT, PSJ_LOGINID_REG, PSJ_KID_CODE) VALUES ('2014-02-12 11:45:08.8', '2014-02-12 00:00:00.0', 0, N'I', N'62', N'2', N'14', N'20081', N'', N'140201', N'', null, N'', N'33671', null, N'', null, N'USD', N'1.000000', null, N'270.00', N'140201', N'140501', N'0', N'0', null, N'HDG2375', null, null, N'', null, N'', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 286832, null, null, null, null, null, null, null, N'South African attorney''s charge (Inv. no. HDG2375)', null, null);");
    DbTestUtils.executeSql(connectionManager.getDataSource(),
                           "INSERT INTO dbo.EXACT_P_S_JOURNAL(PSJ_SAVED_DATE, PSJ_EXPORTED_DATE, PSJ_LINE_NUMBER, PSJ_JOURNAL_TYPE, PSJ_JOURNAL_NUMBER, PSJ_PERIOD, PSJ_FINANCIAL_YEAR, PSJ_ENTRY_NUMBER, PSJ_DESCRIPTION, PSJ_DATE, PSJ_GENERAL_LEDGER_ACCOUNT, PSJ_OFFSET_ACCOUNT, PSJ_DEBTOR_NUMBER, PSJ_CREDITOR_NUMBER, PSJ_OUTSTANDING_INVOICE_NUM, PSJ_AMOUNT, PSJ_JOURNALIZE_FC, PSJ_CURRENCY, PSJ_EXCHANGE_RATE, PSJ_PAYMENT_CHARGE_DISCOUNT, PSJ_AMOUNT_P_C_D, PSJ_DUE_DATE_INVOICE, PSJ_DUE_DATE_PAYMENT, PSJ_VAT_CODE, PSJ_VAT_AMOUNT, PSJ_WEEK_NUMBER, PSJ_PAYMENT_REF, PSJ_PAYMENT_METHOD, PSJ_AMOUNT_BLOCKED_ACCOUNT, PSJ_COST_CENTER, PSJ_COST_UNIT, PSJ_QUANTITY, PSJ_WRITE_OFF_CODE, PSJ_REVERSAL_ENTRY, PSJ_PROJECT_CODE, PSJ_AMOUNT_REVENUE, PSJ_AMOUNT_EXPENSES, PSJ_NUMBER_OF_REVENUES, PSJ_NUMBER_OF_EXPENSES, PSJ_COST_CENTER_2, PSJ_PROJECT_DESCRIPTION, PSJ_COST_CATEGORY, PSJ_JOURNAL_LABEL, PSJ_CATEGORY_TYPE, PSJ_CASE_COUNTRY_CODE, PSJ_CASE_TYPE, PSJ_SAVED_DATE_STR, PSJ_DUE_DATE_INVOICE_STR, PSJ_DUE_DATE_PAYMENT_STR, PSJ_TRANS_ID, PSJ_CASE_ID, PSJ_CHECKSUM, PSJ_WORKCODE, PSJ_LOGINID, PSJ_DEP_COSTCENTER, PSJ_OLD_CASE_ID, PSJ_WORKCODE_TYPE, PSJ_COMMENT, PSJ_LOGINID_REG, PSJ_KID_CODE) VALUES ('2014-02-12 11:45:08.8', '2014-02-12 00:00:00.0', 1, N'I', N'62', N'2', N'14', N'20081', N'T31448ZA09', N'140201', null, null, N'', N'33671', null, N'45.00', null, N'USD', N'1.073767', null, N'270.00', null, null, N'0', N'0', null, null, null, null, N'T', N'ZA', N'1', null, null, N'AC', null, null, null, null, null, N'Egg Globe Device (EP/Afric', null, null, null, null, null, null, null, null, 286832, 59206, null, N'X41', N'RRE', null, null, N'D', N'South African attorney''s charge (Inv. no. HDG2375)', null, null);");
    DbTestUtils.executeSql(connectionManager.getDataSource(),
                           "INSERT INTO dbo.EXACT_P_S_JOURNAL(PSJ_SAVED_DATE, PSJ_EXPORTED_DATE, PSJ_LINE_NUMBER, PSJ_JOURNAL_TYPE, PSJ_JOURNAL_NUMBER, PSJ_PERIOD, PSJ_FINANCIAL_YEAR, PSJ_ENTRY_NUMBER, PSJ_DESCRIPTION, PSJ_DATE, PSJ_GENERAL_LEDGER_ACCOUNT, PSJ_OFFSET_ACCOUNT, PSJ_DEBTOR_NUMBER, PSJ_CREDITOR_NUMBER, PSJ_OUTSTANDING_INVOICE_NUM, PSJ_AMOUNT, PSJ_JOURNALIZE_FC, PSJ_CURRENCY, PSJ_EXCHANGE_RATE, PSJ_PAYMENT_CHARGE_DISCOUNT, PSJ_AMOUNT_P_C_D, PSJ_DUE_DATE_INVOICE, PSJ_DUE_DATE_PAYMENT, PSJ_VAT_CODE, PSJ_VAT_AMOUNT, PSJ_WEEK_NUMBER, PSJ_PAYMENT_REF, PSJ_PAYMENT_METHOD, PSJ_AMOUNT_BLOCKED_ACCOUNT, PSJ_COST_CENTER, PSJ_COST_UNIT, PSJ_QUANTITY, PSJ_WRITE_OFF_CODE, PSJ_REVERSAL_ENTRY, PSJ_PROJECT_CODE, PSJ_AMOUNT_REVENUE, PSJ_AMOUNT_EXPENSES, PSJ_NUMBER_OF_REVENUES, PSJ_NUMBER_OF_EXPENSES, PSJ_COST_CENTER_2, PSJ_PROJECT_DESCRIPTION, PSJ_COST_CATEGORY, PSJ_JOURNAL_LABEL, PSJ_CATEGORY_TYPE, PSJ_CASE_COUNTRY_CODE, PSJ_CASE_TYPE, PSJ_SAVED_DATE_STR, PSJ_DUE_DATE_INVOICE_STR, PSJ_DUE_DATE_PAYMENT_STR, PSJ_TRANS_ID, PSJ_CASE_ID, PSJ_CHECKSUM, PSJ_WORKCODE, PSJ_LOGINID, PSJ_DEP_COSTCENTER, PSJ_OLD_CASE_ID, PSJ_WORKCODE_TYPE, PSJ_COMMENT, PSJ_LOGINID_REG, PSJ_KID_CODE) VALUES ('2014-02-12 11:45:08.8', '2014-02-12 00:00:00.0', 2, N'I', N'62', N'2', N'14', N'20081', N'T31448ZA35', N'140201', null, null, N'', N'33671', null, N'45.00', null, N'USD', N'1.073767', null, N'270.00', null, null, N'0', N'0', null, null, null, null, N'T', N'ZA', N'1', null, null, N'AC', null, null, null, null, null, N'Egg Globe Device (EP/Afric', null, null, null, null, null, null, null, null, 286832, 59207, null, N'X41', N'RRE', null, null, N'D', N'South African attorney''s charge (Inv. no. HDG2375)', null, null);");
    DbTestUtils.executeSql(connectionManager.getDataSource(),
                           "INSERT INTO dbo.EXACT_P_S_JOURNAL(PSJ_SAVED_DATE, PSJ_EXPORTED_DATE, PSJ_LINE_NUMBER, PSJ_JOURNAL_TYPE, PSJ_JOURNAL_NUMBER, PSJ_PERIOD, PSJ_FINANCIAL_YEAR, PSJ_ENTRY_NUMBER, PSJ_DESCRIPTION, PSJ_DATE, PSJ_GENERAL_LEDGER_ACCOUNT, PSJ_OFFSET_ACCOUNT, PSJ_DEBTOR_NUMBER, PSJ_CREDITOR_NUMBER, PSJ_OUTSTANDING_INVOICE_NUM, PSJ_AMOUNT, PSJ_JOURNALIZE_FC, PSJ_CURRENCY, PSJ_EXCHANGE_RATE, PSJ_PAYMENT_CHARGE_DISCOUNT, PSJ_AMOUNT_P_C_D, PSJ_DUE_DATE_INVOICE, PSJ_DUE_DATE_PAYMENT, PSJ_VAT_CODE, PSJ_VAT_AMOUNT, PSJ_WEEK_NUMBER, PSJ_PAYMENT_REF, PSJ_PAYMENT_METHOD, PSJ_AMOUNT_BLOCKED_ACCOUNT, PSJ_COST_CENTER, PSJ_COST_UNIT, PSJ_QUANTITY, PSJ_WRITE_OFF_CODE, PSJ_REVERSAL_ENTRY, PSJ_PROJECT_CODE, PSJ_AMOUNT_REVENUE, PSJ_AMOUNT_EXPENSES, PSJ_NUMBER_OF_REVENUES, PSJ_NUMBER_OF_EXPENSES, PSJ_COST_CENTER_2, PSJ_PROJECT_DESCRIPTION, PSJ_COST_CATEGORY, PSJ_JOURNAL_LABEL, PSJ_CATEGORY_TYPE, PSJ_CASE_COUNTRY_CODE, PSJ_CASE_TYPE, PSJ_SAVED_DATE_STR, PSJ_DUE_DATE_INVOICE_STR, PSJ_DUE_DATE_PAYMENT_STR, PSJ_TRANS_ID, PSJ_CASE_ID, PSJ_CHECKSUM, PSJ_WORKCODE, PSJ_LOGINID, PSJ_DEP_COSTCENTER, PSJ_OLD_CASE_ID, PSJ_WORKCODE_TYPE, PSJ_COMMENT, PSJ_LOGINID_REG, PSJ_KID_CODE) VALUES ('2014-02-12 11:45:08.8', '2014-02-12 00:00:00.0', 3, N'I', N'62', N'2', N'14', N'20081', N'T31448ZA38', N'140201', null, null, N'', N'33671', null, N'45.00', null, N'USD', N'1.073767', null, N'270.00', null, null, N'0', N'0', null, null, null, null, N'T', N'ZA', N'1', null, null, N'AC', null, null, null, null, null, N'Egg Globe Device (EP/Afric', null, null, null, null, null, null, null, null, 286832, 59209, null, N'X41', N'RRE', null, null, N'D', N'South African attorney''s charge (Inv. no. HDG2375)', null, null);");
    DbTestUtils.executeSql(connectionManager.getDataSource(),
                           "INSERT INTO dbo.EXACT_P_S_JOURNAL(PSJ_SAVED_DATE, PSJ_EXPORTED_DATE, PSJ_LINE_NUMBER, PSJ_JOURNAL_TYPE, PSJ_JOURNAL_NUMBER, PSJ_PERIOD, PSJ_FINANCIAL_YEAR, PSJ_ENTRY_NUMBER, PSJ_DESCRIPTION, PSJ_DATE, PSJ_GENERAL_LEDGER_ACCOUNT, PSJ_OFFSET_ACCOUNT, PSJ_DEBTOR_NUMBER, PSJ_CREDITOR_NUMBER, PSJ_OUTSTANDING_INVOICE_NUM, PSJ_AMOUNT, PSJ_JOURNALIZE_FC, PSJ_CURRENCY, PSJ_EXCHANGE_RATE, PSJ_PAYMENT_CHARGE_DISCOUNT, PSJ_AMOUNT_P_C_D, PSJ_DUE_DATE_INVOICE, PSJ_DUE_DATE_PAYMENT, PSJ_VAT_CODE, PSJ_VAT_AMOUNT, PSJ_WEEK_NUMBER, PSJ_PAYMENT_REF, PSJ_PAYMENT_METHOD, PSJ_AMOUNT_BLOCKED_ACCOUNT, PSJ_COST_CENTER, PSJ_COST_UNIT, PSJ_QUANTITY, PSJ_WRITE_OFF_CODE, PSJ_REVERSAL_ENTRY, PSJ_PROJECT_CODE, PSJ_AMOUNT_REVENUE, PSJ_AMOUNT_EXPENSES, PSJ_NUMBER_OF_REVENUES, PSJ_NUMBER_OF_EXPENSES, PSJ_COST_CENTER_2, PSJ_PROJECT_DESCRIPTION, PSJ_COST_CATEGORY, PSJ_JOURNAL_LABEL, PSJ_CATEGORY_TYPE, PSJ_CASE_COUNTRY_CODE, PSJ_CASE_TYPE, PSJ_SAVED_DATE_STR, PSJ_DUE_DATE_INVOICE_STR, PSJ_DUE_DATE_PAYMENT_STR, PSJ_TRANS_ID, PSJ_CASE_ID, PSJ_CHECKSUM, PSJ_WORKCODE, PSJ_LOGINID, PSJ_DEP_COSTCENTER, PSJ_OLD_CASE_ID, PSJ_WORKCODE_TYPE, PSJ_COMMENT, PSJ_LOGINID_REG, PSJ_KID_CODE) VALUES ('2014-02-12 11:45:08.8', '2014-02-12 00:00:00.0', 4, N'I', N'62', N'2', N'14', N'20081', N'T31448ZA41', N'140201', null, null, N'', N'33671', null, N'45.00', null, N'USD', N'1.073767', null, N'270.00', null, null, N'0', N'0', null, null, null, null, N'T', N'ZA', N'1', null, null, N'AC', null, null, null, null, null, N'Egg Globe Device (EP/Afric', null, null, null, null, null, null, null, null, 286832, 59210, null, N'X41', N'RRE', null, null, N'D', N'South African attorney''s charge (Inv. no. HDG2375)', null, null);");
    DbTestUtils.executeSql(connectionManager.getDataSource(),
                           "INSERT INTO dbo.EXACT_P_S_JOURNAL(PSJ_SAVED_DATE, PSJ_EXPORTED_DATE, PSJ_LINE_NUMBER, PSJ_JOURNAL_TYPE, PSJ_JOURNAL_NUMBER, PSJ_PERIOD, PSJ_FINANCIAL_YEAR, PSJ_ENTRY_NUMBER, PSJ_DESCRIPTION, PSJ_DATE, PSJ_GENERAL_LEDGER_ACCOUNT, PSJ_OFFSET_ACCOUNT, PSJ_DEBTOR_NUMBER, PSJ_CREDITOR_NUMBER, PSJ_OUTSTANDING_INVOICE_NUM, PSJ_AMOUNT, PSJ_JOURNALIZE_FC, PSJ_CURRENCY, PSJ_EXCHANGE_RATE, PSJ_PAYMENT_CHARGE_DISCOUNT, PSJ_AMOUNT_P_C_D, PSJ_DUE_DATE_INVOICE, PSJ_DUE_DATE_PAYMENT, PSJ_VAT_CODE, PSJ_VAT_AMOUNT, PSJ_WEEK_NUMBER, PSJ_PAYMENT_REF, PSJ_PAYMENT_METHOD, PSJ_AMOUNT_BLOCKED_ACCOUNT, PSJ_COST_CENTER, PSJ_COST_UNIT, PSJ_QUANTITY, PSJ_WRITE_OFF_CODE, PSJ_REVERSAL_ENTRY, PSJ_PROJECT_CODE, PSJ_AMOUNT_REVENUE, PSJ_AMOUNT_EXPENSES, PSJ_NUMBER_OF_REVENUES, PSJ_NUMBER_OF_EXPENSES, PSJ_COST_CENTER_2, PSJ_PROJECT_DESCRIPTION, PSJ_COST_CATEGORY, PSJ_JOURNAL_LABEL, PSJ_CATEGORY_TYPE, PSJ_CASE_COUNTRY_CODE, PSJ_CASE_TYPE, PSJ_SAVED_DATE_STR, PSJ_DUE_DATE_INVOICE_STR, PSJ_DUE_DATE_PAYMENT_STR, PSJ_TRANS_ID, PSJ_CASE_ID, PSJ_CHECKSUM, PSJ_WORKCODE, PSJ_LOGINID, PSJ_DEP_COSTCENTER, PSJ_OLD_CASE_ID, PSJ_WORKCODE_TYPE, PSJ_COMMENT, PSJ_LOGINID_REG, PSJ_KID_CODE) VALUES ('2014-02-12 11:45:08.8', '2014-02-12 00:00:00.0', 5, N'I', N'62', N'2', N'14', N'20081', N'T31448ZA42', N'140201', null, null, N'', N'33671', null, N'45.00', null, N'USD', N'1.073767', null, N'270.00', null, null, N'0', N'0', null, null, null, null, N'T', N'ZA', N'1', null, null, N'AC', null, null, null, null, null, N'Egg Globe Device (EP/Afric', null, null, null, null, null, null, null, null, 286832, 59211, null, N'X41', N'RRE', null, null, N'D', N'South African attorney''s charge (Inv. no. HDG2375)', null, null);");
    DbTestUtils.executeSql(connectionManager.getDataSource(),
                           "INSERT INTO dbo.EXACT_P_S_JOURNAL(PSJ_SAVED_DATE, PSJ_EXPORTED_DATE, PSJ_LINE_NUMBER, PSJ_JOURNAL_TYPE, PSJ_JOURNAL_NUMBER, PSJ_PERIOD, PSJ_FINANCIAL_YEAR, PSJ_ENTRY_NUMBER, PSJ_DESCRIPTION, PSJ_DATE, PSJ_GENERAL_LEDGER_ACCOUNT, PSJ_OFFSET_ACCOUNT, PSJ_DEBTOR_NUMBER, PSJ_CREDITOR_NUMBER, PSJ_OUTSTANDING_INVOICE_NUM, PSJ_AMOUNT, PSJ_JOURNALIZE_FC, PSJ_CURRENCY, PSJ_EXCHANGE_RATE, PSJ_PAYMENT_CHARGE_DISCOUNT, PSJ_AMOUNT_P_C_D, PSJ_DUE_DATE_INVOICE, PSJ_DUE_DATE_PAYMENT, PSJ_VAT_CODE, PSJ_VAT_AMOUNT, PSJ_WEEK_NUMBER, PSJ_PAYMENT_REF, PSJ_PAYMENT_METHOD, PSJ_AMOUNT_BLOCKED_ACCOUNT, PSJ_COST_CENTER, PSJ_COST_UNIT, PSJ_QUANTITY, PSJ_WRITE_OFF_CODE, PSJ_REVERSAL_ENTRY, PSJ_PROJECT_CODE, PSJ_AMOUNT_REVENUE, PSJ_AMOUNT_EXPENSES, PSJ_NUMBER_OF_REVENUES, PSJ_NUMBER_OF_EXPENSES, PSJ_COST_CENTER_2, PSJ_PROJECT_DESCRIPTION, PSJ_COST_CATEGORY, PSJ_JOURNAL_LABEL, PSJ_CATEGORY_TYPE, PSJ_CASE_COUNTRY_CODE, PSJ_CASE_TYPE, PSJ_SAVED_DATE_STR, PSJ_DUE_DATE_INVOICE_STR, PSJ_DUE_DATE_PAYMENT_STR, PSJ_TRANS_ID, PSJ_CASE_ID, PSJ_CHECKSUM, PSJ_WORKCODE, PSJ_LOGINID, PSJ_DEP_COSTCENTER, PSJ_OLD_CASE_ID, PSJ_WORKCODE_TYPE, PSJ_COMMENT, PSJ_LOGINID_REG, PSJ_KID_CODE) VALUES ('2014-02-12 11:45:08.8', '2014-02-12 00:00:00.0', 6, N'I', N'62', N'2', N'14', N'20081', N'T31448ZA45', N'140201', null, null, N'', N'33671', null, N'45.00', null, N'USD', N'1.073767', null, N'270.00', null, null, N'0', N'0', null, null, null, null, N'T', N'ZA', N'1', null, null, N'AC', null, null, null, null, null, N'Egg Globe Device (EP/Afric', null, null, null, null, null, null, null, null, 286832, 59212, null, N'X41', N'RRE', null, null, N'D', N'South African attorney''s charge (Inv. no. HDG2375)', null, null);");
    PatriciaInvoice patriciaInvoice = exactTableGateway.getPatriciaInvoice(20081, null);
    Assert.assertNotNull(patriciaInvoice);
    Assert.assertNotNull(patriciaInvoice.getJournalLines());
    Assert.assertEquals(patriciaInvoice.getJournalLines().size(), 7);

    List<LineItem> xeroLineItems =
        xeroFromPatriciaTransformer
            .extractXeroLineItems(patriciaInvoice, "AU", TransactionType.INVOICE, null);
    Assert.assertNotNull(xeroLineItems);
    Assert.assertNotNull(xeroLineItems);
    Assert.assertEquals(xeroLineItems.size(), 6);

    Assert.assertTrue(
        xeroFromPatriciaTransformer.areTotalsEqual(patriciaInvoice, xeroLineItems, null));

    Invoice
        invoice =
        xeroFromPatriciaTransformer
            .createXeroInvoice(patriciaInvoice, new Contact(), xeroLineItems, "AU", null);
    Assert.assertNotNull(invoice);
    Assert.assertEquals(invoice.getInvoiceNumber(), "HDG2375");
  }


  @Test
  public void testCreateLineItems() throws Exception {
    DbTestUtils.executeSql(connectionManager.getDataSource(),
                           "INSERT INTO dbo.EXACT_P_S_JOURNAL(PSJ_SAVED_DATE, PSJ_EXPORTED_DATE, PSJ_LINE_NUMBER, PSJ_JOURNAL_TYPE, PSJ_JOURNAL_NUMBER, PSJ_PERIOD, PSJ_FINANCIAL_YEAR, PSJ_ENTRY_NUMBER, PSJ_DESCRIPTION, PSJ_DATE, PSJ_GENERAL_LEDGER_ACCOUNT, PSJ_OFFSET_ACCOUNT, PSJ_DEBTOR_NUMBER, PSJ_CREDITOR_NUMBER, PSJ_OUTSTANDING_INVOICE_NUM, PSJ_AMOUNT, PSJ_JOURNALIZE_FC, PSJ_CURRENCY, PSJ_EXCHANGE_RATE, PSJ_PAYMENT_CHARGE_DISCOUNT, PSJ_AMOUNT_P_C_D, PSJ_DUE_DATE_INVOICE, PSJ_DUE_DATE_PAYMENT, PSJ_VAT_CODE, PSJ_VAT_AMOUNT, PSJ_WEEK_NUMBER, PSJ_PAYMENT_REF, PSJ_PAYMENT_METHOD, PSJ_AMOUNT_BLOCKED_ACCOUNT, PSJ_COST_CENTER, PSJ_COST_UNIT, PSJ_QUANTITY, PSJ_WRITE_OFF_CODE, PSJ_REVERSAL_ENTRY, PSJ_PROJECT_CODE, PSJ_AMOUNT_REVENUE, PSJ_AMOUNT_EXPENSES, PSJ_NUMBER_OF_REVENUES, PSJ_NUMBER_OF_EXPENSES, PSJ_COST_CENTER_2, PSJ_PROJECT_DESCRIPTION, PSJ_COST_CATEGORY, PSJ_JOURNAL_LABEL, PSJ_CATEGORY_TYPE, PSJ_CASE_COUNTRY_CODE, PSJ_CASE_TYPE, PSJ_SAVED_DATE_STR, PSJ_DUE_DATE_INVOICE_STR, PSJ_DUE_DATE_PAYMENT_STR, PSJ_TRANS_ID, PSJ_CASE_ID, PSJ_CHECKSUM, PSJ_WORKCODE, PSJ_LOGINID, PSJ_DEP_COSTCENTER, PSJ_OLD_CASE_ID, PSJ_WORKCODE_TYPE, PSJ_COMMENT, PSJ_LOGINID_REG, PSJ_KID_CODE) VALUES ('2014-02-13 09:44:11.813', '1905-05-14 00:00:00.0', 0, N'V', N'52', N'2', N'14', N'300036', N'P31133AU00', N'140213', N'', null, N'36976', N'', null, null, null, N'EUR', N'1.323823', null, N'642.53', N'140213', N'140227', null, null, null, null, null, null, N'SC', null, null, null, null, null, null, null, null, null, null, N'Anti-mosquito net rope mov', null, null, N'', null, null, null, null, null, 287298, 57819, N'', null, null, null, null, null, null, null, null);");
    DbTestUtils.executeSql(connectionManager.getDataSource(),
                           "INSERT INTO dbo.EXACT_P_S_JOURNAL(PSJ_SAVED_DATE, PSJ_EXPORTED_DATE, PSJ_LINE_NUMBER, PSJ_JOURNAL_TYPE, PSJ_JOURNAL_NUMBER, PSJ_PERIOD, PSJ_FINANCIAL_YEAR, PSJ_ENTRY_NUMBER, PSJ_DESCRIPTION, PSJ_DATE, PSJ_GENERAL_LEDGER_ACCOUNT, PSJ_OFFSET_ACCOUNT, PSJ_DEBTOR_NUMBER, PSJ_CREDITOR_NUMBER, PSJ_OUTSTANDING_INVOICE_NUM, PSJ_AMOUNT, PSJ_JOURNALIZE_FC, PSJ_CURRENCY, PSJ_EXCHANGE_RATE, PSJ_PAYMENT_CHARGE_DISCOUNT, PSJ_AMOUNT_P_C_D, PSJ_DUE_DATE_INVOICE, PSJ_DUE_DATE_PAYMENT, PSJ_VAT_CODE, PSJ_VAT_AMOUNT, PSJ_WEEK_NUMBER, PSJ_PAYMENT_REF, PSJ_PAYMENT_METHOD, PSJ_AMOUNT_BLOCKED_ACCOUNT, PSJ_COST_CENTER, PSJ_COST_UNIT, PSJ_QUANTITY, PSJ_WRITE_OFF_CODE, PSJ_REVERSAL_ENTRY, PSJ_PROJECT_CODE, PSJ_AMOUNT_REVENUE, PSJ_AMOUNT_EXPENSES, PSJ_NUMBER_OF_REVENUES, PSJ_NUMBER_OF_EXPENSES, PSJ_COST_CENTER_2, PSJ_PROJECT_DESCRIPTION, PSJ_COST_CATEGORY, PSJ_JOURNAL_LABEL, PSJ_CATEGORY_TYPE, PSJ_CASE_COUNTRY_CODE, PSJ_CASE_TYPE, PSJ_SAVED_DATE_STR, PSJ_DUE_DATE_INVOICE_STR, PSJ_DUE_DATE_PAYMENT_STR, PSJ_TRANS_ID, PSJ_CASE_ID, PSJ_CHECKSUM, PSJ_WORKCODE, PSJ_LOGINID, PSJ_DEP_COSTCENTER, PSJ_OLD_CASE_ID, PSJ_WORKCODE_TYPE, PSJ_COMMENT, PSJ_LOGINID_REG, PSJ_KID_CODE) VALUES ('2014-02-13 09:44:11.813', '1905-05-14 00:00:00.0', 1, N'V', N'52', N'2', N'14', N'300036', N'P31133AU00', N'140213', null, null, N'36976', N'', null, N'541.14', null, N'EUR', N'1.323823', null, null, null, null, N'4', N'0', null, N'1', null, null, N'P', N'AU', N'58.00', null, null, N'AB', null, null, null, null, null, N'Anti-mosquito net rope mov', N'800', null, N'', null, null, null, null, null, 287298, 57819, N'', N'5000', N'GV', null, null, N'T', null, null, null);");
    DbTestUtils.executeSql(connectionManager.getDataSource(),
                           "INSERT INTO dbo.EXACT_P_S_JOURNAL(PSJ_SAVED_DATE, PSJ_EXPORTED_DATE, PSJ_LINE_NUMBER, PSJ_JOURNAL_TYPE, PSJ_JOURNAL_NUMBER, PSJ_PERIOD, PSJ_FINANCIAL_YEAR, PSJ_ENTRY_NUMBER, PSJ_DESCRIPTION, PSJ_DATE, PSJ_GENERAL_LEDGER_ACCOUNT, PSJ_OFFSET_ACCOUNT, PSJ_DEBTOR_NUMBER, PSJ_CREDITOR_NUMBER, PSJ_OUTSTANDING_INVOICE_NUM, PSJ_AMOUNT, PSJ_JOURNALIZE_FC, PSJ_CURRENCY, PSJ_EXCHANGE_RATE, PSJ_PAYMENT_CHARGE_DISCOUNT, PSJ_AMOUNT_P_C_D, PSJ_DUE_DATE_INVOICE, PSJ_DUE_DATE_PAYMENT, PSJ_VAT_CODE, PSJ_VAT_AMOUNT, PSJ_WEEK_NUMBER, PSJ_PAYMENT_REF, PSJ_PAYMENT_METHOD, PSJ_AMOUNT_BLOCKED_ACCOUNT, PSJ_COST_CENTER, PSJ_COST_UNIT, PSJ_QUANTITY, PSJ_WRITE_OFF_CODE, PSJ_REVERSAL_ENTRY, PSJ_PROJECT_CODE, PSJ_AMOUNT_REVENUE, PSJ_AMOUNT_EXPENSES, PSJ_NUMBER_OF_REVENUES, PSJ_NUMBER_OF_EXPENSES, PSJ_COST_CENTER_2, PSJ_PROJECT_DESCRIPTION, PSJ_COST_CATEGORY, PSJ_JOURNAL_LABEL, PSJ_CATEGORY_TYPE, PSJ_CASE_COUNTRY_CODE, PSJ_CASE_TYPE, PSJ_SAVED_DATE_STR, PSJ_DUE_DATE_INVOICE_STR, PSJ_DUE_DATE_PAYMENT_STR, PSJ_TRANS_ID, PSJ_CASE_ID, PSJ_CHECKSUM, PSJ_WORKCODE, PSJ_LOGINID, PSJ_DEP_COSTCENTER, PSJ_OLD_CASE_ID, PSJ_WORKCODE_TYPE, PSJ_COMMENT, PSJ_LOGINID_REG, PSJ_KID_CODE) VALUES ('2014-02-13 09:44:11.813', '1905-05-14 00:00:00.0', 2, N'V', N'52', N'2', N'14', N'300036', N'P31133AU00', N'140213', null, null, N'36976', N'', null, N'260.00', null, N'EUR', N'1.323823', null, null, null, null, N'4', N'0', null, N'1', null, null, N'P', N'AU', N'1.00', null, null, N'AB', null, null, null, null, null, N'Anti-mosquito net rope mov', N'1003', null, N'', null, null, null, null, null, 287298, 57819, N'', N'L1670', N'CM', null, null, N'S', null, null, null);");
    DbTestUtils.executeSql(connectionManager.getDataSource(),
                           "INSERT INTO dbo.EXACT_P_S_JOURNAL(PSJ_SAVED_DATE, PSJ_EXPORTED_DATE, PSJ_LINE_NUMBER, PSJ_JOURNAL_TYPE, PSJ_JOURNAL_NUMBER, PSJ_PERIOD, PSJ_FINANCIAL_YEAR, PSJ_ENTRY_NUMBER, PSJ_DESCRIPTION, PSJ_DATE, PSJ_GENERAL_LEDGER_ACCOUNT, PSJ_OFFSET_ACCOUNT, PSJ_DEBTOR_NUMBER, PSJ_CREDITOR_NUMBER, PSJ_OUTSTANDING_INVOICE_NUM, PSJ_AMOUNT, PSJ_JOURNALIZE_FC, PSJ_CURRENCY, PSJ_EXCHANGE_RATE, PSJ_PAYMENT_CHARGE_DISCOUNT, PSJ_AMOUNT_P_C_D, PSJ_DUE_DATE_INVOICE, PSJ_DUE_DATE_PAYMENT, PSJ_VAT_CODE, PSJ_VAT_AMOUNT, PSJ_WEEK_NUMBER, PSJ_PAYMENT_REF, PSJ_PAYMENT_METHOD, PSJ_AMOUNT_BLOCKED_ACCOUNT, PSJ_COST_CENTER, PSJ_COST_UNIT, PSJ_QUANTITY, PSJ_WRITE_OFF_CODE, PSJ_REVERSAL_ENTRY, PSJ_PROJECT_CODE, PSJ_AMOUNT_REVENUE, PSJ_AMOUNT_EXPENSES, PSJ_NUMBER_OF_REVENUES, PSJ_NUMBER_OF_EXPENSES, PSJ_COST_CENTER_2, PSJ_PROJECT_DESCRIPTION, PSJ_COST_CATEGORY, PSJ_JOURNAL_LABEL, PSJ_CATEGORY_TYPE, PSJ_CASE_COUNTRY_CODE, PSJ_CASE_TYPE, PSJ_SAVED_DATE_STR, PSJ_DUE_DATE_INVOICE_STR, PSJ_DUE_DATE_PAYMENT_STR, PSJ_TRANS_ID, PSJ_CASE_ID, PSJ_CHECKSUM, PSJ_WORKCODE, PSJ_LOGINID, PSJ_DEP_COSTCENTER, PSJ_OLD_CASE_ID, PSJ_WORKCODE_TYPE, PSJ_COMMENT, PSJ_LOGINID_REG, PSJ_KID_CODE) VALUES ('2014-02-13 09:44:11.813', '1905-05-14 00:00:00.0', 3, N'V', N'52', N'2', N'14', N'300036', N'P31133AU00', N'140213', null, null, N'36976', N'', null, N'-158.61', null, N'EUR', N'1.323823', null, null, null, null, N'4', N'0', null, N'1', null, null, N'P', N'AU', N'-17.00', null, null, N'AB', null, null, null, null, null, N'Anti-mosquito net rope mov', N'1152', null, N'', null, null, null, null, null, 287298, 57819, N'', N'W0030', N'GV', null, null, N'T', null, null, null);");
    PatriciaInvoice patriciaInvoice = exactTableGateway.getPatriciaInvoice(300036, null);
    Assert.assertNotNull(patriciaInvoice);
    Assert.assertNotNull(patriciaInvoice.getJournalLines());
    Assert.assertEquals(patriciaInvoice.getJournalLines().size(), 4);

    final
    List<LineItem>
        xeroLineItems =
        xeroFromPatriciaTransformer
            .extractXeroLineItems(patriciaInvoice, "AU", TransactionType.INVOICE, null);
    Assert.assertNotNull(xeroLineItems);
    Assert.assertNotNull(xeroLineItems);
    Assert.assertEquals(xeroLineItems.size(), 3);

    Assert.assertTrue(
        xeroFromPatriciaTransformer.areTotalsEqual(patriciaInvoice, xeroLineItems, null));

    Invoice invoice =
        xeroFromPatriciaTransformer
            .createXeroInvoice(patriciaInvoice, new Contact(), xeroLineItems, "AU", null);
    Assert.assertNotNull(invoice);
  }

}
